config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {:registrations => "users/registrations"}

  root 'games#index'

  resources :players
  resources :teams
  get 'games/schedule_week', to: 'games#new_week'
  post 'games/schedule_week', to: 'games#create_week'

  resources :games do
    post 'update_score', to: 'games#update_score'
    resources :team_games, only: [:create]
  end


  resources :users, only: [:index, :show, :destroy]
  patch 'users/:id', to: 'users#update'

  resources :game_stats, only: [:update]
  resources :schedules
  resources :invitations

  resources :commissioner, only: [:index]
  get 'commissioner/getplayers', to: 'commissioner#get_players', as: :get_players
  get 'commissioner/loadstats', to: 'commissioner#load_stats', as: :load_stats
  get 'commissioner/export_week', to: 'commissioner#export_week', as: :export_week

  get 'games/:id/scorekeep', to: 'games#scorekeep', as: :scorekeep_games

  get 'createschedule', to: 'games#create_schedule', as: :schedule_games
  get 'deleteall', to: 'games#delete_all', as: :destroy_games

end

app/controllers/commissioner_controller.rb
require 'google/api_client'
require 'google_drive'

class CommissionerController < ApplicationController
  before_filter :authenticate_user!
  force_ssl unless Rails.env.development?

  def index
    redirect_to root_url unless current_user.admin || current_user.commissioner
  end

  def get_players
    if Player.exists?
      flash[:alert] = "There are already players in the system"
      redirect_to :back
    else
      key = auth(get_players_url, nil)
      if !key.blank?
        initial = Player.all.size
        GetPlayers.from_google(key)
        flash[:success] = "Added #{Player.all.size - initial} players to the database"
        redirect_to commissioner_index_path
      end
    end
  end

  def load_stats
    if GameStat.where(week: 0).where('created_at < updated_at').exists?
      flash[:alert] = "There are already stats for the first week"
      redirect_to :back
      return
    end
    key = auth(load_stats_url, nil)
    if !key.blank?
      GetPlayersStats.from_google(key)
      flash[:success] = "Loaded Players Stats"
      redirect_to commissioner_index_path
    end
  end

  def export_week
    key = auth(export_week_url, params[:week])
    if !key.blank?
      week = params[:week] || params[:state]
      ExportData.perform_async(key, week.to_i)
      flash[:alert] = "Exporting week #{week.to_i + 1} in background, feel free to keep using the website"
      redirect_to commissioner_index_path
    end
  end

  private

  def auth(redirect_url, state)
    if session[:google_access_token].blank? || session[:google_token_date].blank? || DateTime.now > DateTime.parse(session[:google_token_date])
      client = Google::APIClient.new
      auth = client.authorization
      auth.update!(
          client_id: ENV['GOOGLE_CLIENT_ID'],
          client_secret: ENV['GOOGLE_CLIENT_SECRET'],
          grant_type: "authorization_code",
          scope: "https://www.googleapis.com/auth/drive ",
          redirect_uri: redirect_url,
          state: state
      )
      if params['code'].blank?
        auth_url = auth.authorization_uri.to_s
        redirect_to auth_url
        ""
      else
        auth.code = request['code']
        auth.fetch_access_token!
        session[:google_access_token] = auth.access_token
        session[:google_token_date] = DateTime.now.advance(hours: 1).to_s
        return auth.access_token
      end
    else
      p "Already have token"
      return session[:google_access_token]
    end
  end
end

app/helpers/commissioner_helper.rb
module CommissionerHelper
end

app/views/commissioner/index.html.erb
<div class="body">
  <div class="add">
    <h3>Add:</h3>
    <div class="btn btn-no-padding"><%= link_to "Player", new_player_path %></div>
    <div class="btn btn-no-padding"><%= link_to "Team", new_team_path %></div>
  </div>

  <div class="output">
    <%= form_tag(export_week_path, method: 'get') do %>
        <h3 class="thin">Export Stats to Google Spreadsheet:</h3>
        <%= select_tag :week, options_for_select((0..Schedule.all.size-1).map {|i| ["Week #{i+1}", i]}) %>
        <%= submit_tag "Export", class: "btn btn-no-paddding" %>
    <% end %>
  </div>

  <div class="schedule">
    <h3>Schedule:</h3>
      <div class="btn btn-no-padding"><%= link_to "Edit Game Schedule", schedules_path %></div>
      <div class="btn btn-no-padding"><%= link_to "Add Games", new_schedule_path %></div>
  </div>

  <div class="load">
    <h3>Load data from Google Spreadsheet:</h3>
    <div class="btn btn-no-padding">
      <%= link_to "Load Players", get_players_path %>
    </div>

    <div class="btn btn-no-padding">
      <%= link_to "Load Stats", load_stats_path %>
    </div>
  </div>
</div>

<script>
    $( "#week" ).select2({
        theme: "bootstrap",
        minimumResultsForSearch: Infinity
    });
</script>