config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {:registrations => "users/registrations"}

  root 'games#index'

  resources :players
  resources :teams
  get 'games/schedule_week', to: 'games#new_week'
  post 'games/schedule_week', to: 'games#create_week'

  resources :games do
    post 'update_score', to: 'games#update_score'
    resources :team_games, only: [:create]
  end


  resources :users, only: [:index, :show, :destroy]
  patch 'users/:id', to: 'users#update'

  resources :game_stats, only: [:update]
  resources :schedules
  resources :invitations

  resources :commissioner, only: [:index]
  get 'commissioner/getplayers', to: 'commissioner#get_players', as: :get_players
  get 'commissioner/loadstats', to: 'commissioner#load_stats', as: :load_stats
  get 'commissioner/export_week', to: 'commissioner#export_week', as: :export_week

  get 'games/:id/scorekeep', to: 'games#scorekeep', as: :scorekeep_games

  get 'createschedule', to: 'games#create_schedule', as: :schedule_games
  get 'deleteall', to: 'games#delete_all', as: :destroy_games

end

app/models/game_stat.rb
class GameStat < ActiveRecord::Base
  FIELDS = %w(Ds Goals Assists Turns Swag)

  belongs_to :player
  belongs_to :team_game
  has_one :team, through: :player
  has_one :game, through: :team_game

  validates :team_game_id, presence: true
  validates :player_id, presence: true, uniqueness: { scope: :team_game_id }

  before_update :update_points
  before_destroy :remove_points

  TYPE = %i(goals assists ds turns swag)
  SCORE = [3, 3, 2, -1, 1]
  VALUE = {"goals": 3, "assists": 3, "ds":2, "turns":-1, "swag":1}

  COUNT = TYPE.zip(SCORE)

  def update_points
    team_game.update_attributes(goals: team_game.goals + (goals - goals_was)) if goals_changed?
    prior_points = self[:points]
    self[:points] = COUNT.inject(0) { |sum, obj| sum + self[obj[0]] * obj[1] }
    player.update_attribute(:points, player.points + points - prior_points)
    # change updating winners in future
    AssignWinners.perform_in(30*60, false) if goals < 2
  end

  def remove_points
    player.update_attribute(:points, player.points - points) unless player.blank?
  end
end

app/controllers/game_stats_controller.rb
class GameStatsController < ApplicationController
  before_filter :authenticate_user!

  def update
    @game_stat = GameStat.find_by(id: params["id"])
    authorize @game_stat
    if @game_stat
      change = params[:op] == "add" ? 1 : -1
      @game_stat.update_attribute(params[:attr], @game_stat[params[:attr]] + change)
    end
    render 'layouts/_flash_messages'
  end
end

app/helpers/game_stats_helper.rb
module GameStatsHelper
end

app/views/game_stats/_edit_row.html.erb
  <td><%= link_to(row.player.name, row.player) %></td>
  <td id="<%= row.id %>points"><%= row.points %></td>
  <% GameStat::TYPE.each do |index| %>
      <td class="editval">
        <div class="whole">
            <%= button_to("", row, remote: true, method: :patch, params: { op: "add", attr: index }, class: "plus #{row.id} #{GameStat::VALUE[index]}", onclick: "updateRow(this)") %>
            <span class="value"><%= row[index] %></span>
            <span class="add1">+</span>
        </div>
        <%= button_to('-', row, remote: true, method: :patch, params: { op: "subtract", attr: index }, class: "minus #{row.id} #{GameStat::VALUE[index]}", onclick: "updateRow(this)") %>
        <script></script>
      </td>
  <% end %>

app/views/game_stats/_row.html.erb
  <td><%= link_to(row.player.name, row.player) %></td>
  <td><%= row.points %></td>
  <% GameStat::TYPE.each do |index| %>
      <td>
        <p><%= row[index] %></p>
      </td>
  <% end %>

app/views/game_stats/_scorekeep_table.html.erb
<div class="stats-table">
  <h3 class="thin"><%= team.name %> (<%= team.color %>): <span class="<%= team.color %>"><%= team_game.goals %></span></h3>
  <table class="table table-bordered table-hover scorekeeptable" id="<%= team.color %>">
    <thead>
      <tr>
        <th class="name">Player</th>
        <th class="points">Points</th>
        <th class="goals">Goals (3)</th>
        <th class="assists">Assists (3)</th>
        <th class="ds">Ds (2)</th>
        <th class="turns">Turns (-1)</th>
        <th class="swag">Swag (1)</th>
      </tr>
    </thead>
    <tbody>
      <% team_game.game_stats.includes(:player).each do |stat| %>
          <tr id="<%= stat.id %>">
            <%= render partial: 'game_stats/edit_row', locals: {row: stat} %>
          </tr>
      <% end %>
    </tbody>
  </table>
  <button type="button" class="btn btn-gray" data-toggle="modal" data-target="#addPlayer<%= team.color %>">
    Add a player to <%= team.color %> Team
  </button>
  <div class="modal fade" id="addPlayer<%= team.color %>" tabindex="-1" role="dialog" aria-labelledby="title">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <%= form_for :player, url: players_path, remote: true do |f| %>
              <div class="form-header">
                  <h2 id="title"><%= team.color %> Team</h2>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              </div>
              <div class="form-body">
                  <p>
                    <%= f.text_field :name, required: true, placeholder: "Name" %>
                  </p>
                  <div class="gender_div">
                    <%= f.radio_button(:gender, 0, checked: true) %>
                    <%= f.label(:gender_0, "Eman") %>
                    <%= f.radio_button(:gender, 1) %>
                    <%= f.label(:gender_1, "Ewo") %>
                  </div>
                  <%= hidden_field_tag 'membership[team_id]', team.id  %>
              </div>
              <div class="form-footer">
                <button type="button" class="btn btn-default btn-gray" data-dismiss="modal">Cancel</button>
                <%= f.submit "Add Player", data: { disable_with: "Please wait...." }, class: "btn" %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {
      $("table#<%= team.color %>").tablesorter();
      sessionStorage['<%= team.color %>'] = parseInt($('span.<%= team.color %>').html());
      $(".gender_div").buttonset();
  });
  $('.modal input[type=submit]').click(function() {
    location.reload();
  });
    $("table#<%= team.color %>").on('click', 'tr > td:nth-child(3) .plus', function () {
        sessionStorage['<%= team.color %>'] = parseInt(sessionStorage['<%= team.color %>']) + 1
        $('span.<%= team.color %>').html(sessionStorage['<%= team.color %>']);
    });
    $("table#<%= team.color %>").on('click', 'tr > td:nth-child(3) .minus', function () {
        sessionStorage['<%= team.color %>'] = parseInt(sessionStorage['<%= team.color %>']) - 1
        $('span.<%= team.color %>').html(sessionStorage['<%= team.color %>']);
    });
  $('#addPlayer<%= team.color %>').on('shown.bs.modal', function () {
      $('#player_name').focus()
  });
</script>

app/views/game_stats/_simple_row.html.erb
<tr>
    <td><%= simple_row.week + 1 %></td>
    <td><%= link_to(simple_row.team_game.game.name, game_path(simple_row.team_game.game)) %></td>
    <td><%= simple_row.points %></td>
    <% GameStat::TYPE.each do |index| %>
        <td>
          <p><%= simple_row[index] %></p>
        </td>
    <% end %>
</tr>

app/views/game_stats/_table.html.erb
<div class="stats-table">
  <h3 class="thin"><%= team.name %> (<%= team.color %>): <span><%= team_game.goals %></span></h3>
    <table class="table table-bordered table-hover table-nonfluid" id="<%= team.color %>">
      <thead>
          <tr>
            <th>Player</th>
            <th>Fantasy Points</th>
            <th>Goals (3)</th>
            <th>Assists (3)</th>
            <th>Ds (2)</th>
            <th>Turns (-1)</th>
            <th>Swag (1)</th>
          </tr>
      </thead>
      <tbody>
      <% team_game.game_stats.order(updated_at: :desc).includes(:player).each do |stat| %>
          <tr id="<%= stat.id %>">
            <%= render partial: 'game_stats/row', locals: {row: stat} %>
          </tr>
      <% end %>
      </tbody>
    </table>
</div>

<script>
    $(document).ready(function()
        {
            $("#<%= team.color %>").tablesorter();
        }
    );
</script>