config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {:registrations => "users/registrations"}

  root 'games#index'

  resources :players
  resources :teams
  get 'games/schedule_week', to: 'games#new_week'
  post 'games/schedule_week', to: 'games#create_week'

  resources :games do
    post 'update_score', to: 'games#update_score'
    resources :team_games, only: [:create]
  end


  resources :users, only: [:index, :show, :destroy]
  patch 'users/:id', to: 'users#update'

  resources :game_stats, only: [:update]
  resources :schedules
  resources :invitations

  resources :commissioner, only: [:index]
  get 'commissioner/getplayers', to: 'commissioner#get_players', as: :get_players
  get 'commissioner/loadstats', to: 'commissioner#load_stats', as: :load_stats
  get 'commissioner/export_week', to: 'commissioner#export_week', as: :export_week

  get 'games/:id/scorekeep', to: 'games#scorekeep', as: :scorekeep_games

  get 'createschedule', to: 'games#create_schedule', as: :schedule_games
  get 'deleteall', to: 'games#delete_all', as: :destroy_games

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert <%= bootstrap_flash_class(key) %> fade in">
      <a href="#" data-dismiss="alert" class="close">x</a>
      <%= value %>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="<%= navbar_active("games")%>"><%= link_to "Games", games_path %></li>
        <li class="<%= navbar_active("teams")%>"><%= link_to "Teams", teams_path %></li>
        <li class="<%= navbar_active("players")%>"><%= link_to "Players", players_path %></li>
        <% if current_user.commissioner || current_user.admin %>
            <li class="<%= navbar_active("commissioner")%>"><%= link_to "Commissioner", commissioner_index_path %></li>
        <% end %>
        <% if current_user.admin %>
            <li class="dropdown <%= navbar_active("admin")%>">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                Admin <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <% if Rails.env.development? %>
                    <li><%= link_to "Delete all games", destroy_games_path %></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "Auto schedule all games", schedule_games_path %></li>
                    <li role="separator" class="divider"></li>
                <% end %>
                <li><%= link_to "Users", users_path %></li>
                <!--li role="separator" class="divider"></li>
                <li><%= link_to "View Invitations", invitations_path %></li>
                <li><%= link_to "Send Invitation", new_invitation_path %></li -->
              </ul>
            </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= navbar_active("users/registrations")%>"><%= link_to "Account", edit_user_registration_path %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
      </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fittfu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
    <% if user_signed_in? %>
        <div class="header">
            <%= render 'layouts/navbar' %>
        </div>
    <% end %>

    <%= render 'layouts/flash_messages' %>
    <%= yield %>

    <%= render 'layouts/footer' %>

</body>
</html>